name: Auto Update Radar Map

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install numpy requests pillow folium branca pandas

      - name: Run Python Script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update map and CSV data" || exit 0
          git push
